packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - oxc-resolver
  - sharp
  - unrs-resolver

patchedDependencies:
  uniffi-bindgen-react-native: patches/uniffi-bindgen-react-native.patch
