name: Check
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Cache Nix Store
        uses: nix-community/cache-nix-action@main
        with:
          primary-key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Load devShell environment
        uses: nicknovitski/nix-develop@main
        with:
          arguments: .#android-remote

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - run: pnpm exec turbo lint:check

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       uses: ./.github/actions/setup
  #     - run: pnpm vitest
  #       env:
  #         NODE_OPTIONS: --max_old_space_size=8192
